#!/bin/bash
SPACE="         "
VAR=AaBbCc
STUFF=Variable.Variable.Variable.Stuff
SENTENCE="How is you?"
echo "Variables added"
echo "VAR is ${VAR}"
echo "STUFF is ${STUFF}"
echo "SENTENCE is ${SENTENCE}"
echo "Now lets break it down"
echo "Part 1:"
echo "${SPACE} - Using ##*. ${STUFF##*.}"
echo "${SPACE} - Using #*.  ${STUFF#*.}"
echo "${SPACE} - Using %%.* ${STUFF%%.*}"
echo "${SPACE} - Using %.*  ${STUFF%.*}"
echo ""
echo "Part 2:"
echo "${SPACE} - Substituting is with are: ${SENTENCE/is/are}"
echo "${SPACE} - Substituting Aa with cC: ${VAR/Aa/cC}"
echo "${SPACE} - Removing Spaces: ${SENTENCE// }"
echo ""
echo "Part 3:"
echo "${SPACE} - Capitalizing the Variables:"
echo "$SPACE $SPACE - $VAR becomes ${VAR^^}"
echo "$SPACE $SPACE - $STUFF becomes ${STUFF^^}"
echo "$SPACE $SPACE - $SENTENCE becomes ${SENTENCE^^}"
echo ""
echo "Part 4:"
echo "${SPACE} - Making the Variables lowercase:"
echo "$SPACE $SPACE - $VAR becomes ${VAR,,}"
echo "$SPACE $SPACE - $STUFF becomes ${STUFF,,}"
echo "$SPACE $SPACE - $SENTENCE becomes ${SENTENCE,,}"
